### ISSUE TITLE
Height of list and rollover

### ISSUE THREAD

**Issue by Jonkheer73** [htilburgs/MMM-MyTraffic#1]
Hi, The script works great.
The only trouble I have is when there is a long list it is not all visible.
Is it possible to create a limit on the height?
Maybe with a rollover function?
Thanks.

**Comment by htilburgs** [comment]
I'm currently working on a new version, but due to privat time issues it's not going as fast as I would like ;-) I'm taking you're question into consideration.

**Comment by htilburgs** [comment]
Update: still not going fast.....

**Comment by ronsondonson-rgb** [comment]
Hey! Is it able to locate german Traffic Jams and language in german?
Thanks!

**Comment by htilburgs** [comment]
@ronsondonson-rgb, Sorry, only dutch traffic jams and only support for Dutch language.

**Comment by htilburgs** [comment]
Currently no time due to new Job.
Maybe later, but no promisses....
